### ISSUE TITLE
Cntrl arrow is not shifting focus only highlight

### ISSUE THREAD

**Issue by MikeyBeez** [pop-os/shell-shortcuts#25]
Thanks for the great software.  I love POP!_OS 20.04.  Nevertheless, ;) After hitting super enter, cntrl arrow moves the highlighting but not the active hint.  So when an arrow is pressed on its own, the tile that was initially selcted with super enter is moved, and not the tile with the highlighting.    Cheers!

**Comment by leviport** [comment]
I see what you mean, although I believe that is intended behavior. In window management mode (`super` + `enter`), `Ctrl` + arrow keys highlights another window while leaving the initially selected window active. This is because once you hit `Enter`, the selected window and the active window swap places. A simple move operation (just arrow keys while in window management mode) cancels the swap operation and moves the active window in a direction. If you want to change the focused window, you have to exit window management mode with `Esc`, change focus, then re-enter window management mode (`super` + `enter`).

**Comment by MikeyBeez** [comment]
Thank you.  This makes sense too.
