### ISSUE TITLE
[Feature Request] Build instructions for getting pop shell shortcuts

### ISSUE THREAD

**Issue by fourstepper** [pop-os/shell-shortcuts#6]
Hello, I am getting an error of not having pop-shell-shortcuts together with pop-shell on my system. How can I install this?

Thanks

![image](https://user-images.githubusercontent.com/49439044/78539090-4d3f3380-77f2-11ea-8c80-cc9fa8fccde7.png)

**Comment by k4st33l** [comment]
First install **rust** package for your distribution that include **cargo** package manager.

Then just compile and install :
```
make
sudo make install
```

**Comment by likern** [comment]
> Hello, I am getting an error of not having pop-shell-shortcuts together with pop-shell on my system. How can I install this?
> 
> Thanks
> 
> ![image](https://user-images.githubusercontent.com/49439044/78539090-4d3f3380-77f2-11ea-8c80-cc9fa8fccde7.png)

error: failed to run custom build command for `glib-sys v0.9.1`

Caused by:
  process didn't exit successfully: `/home/me/Projects/shell-shortcuts/target/release/build/glib-sys-6c2c6f075f4895cd/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.42"` did not exit successfully: exit code: 1
--- stderr
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glib-2.0', required by 'virtual:world', not found
Package 'glib-2.0', required by 'virtual:world', not found


warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:57: target/release/pop-shell-shortcuts] Ошибка 101

**Comment by a6avind** [comment]
you can try `sudo apt-get install libgtk-3-dev`
